spring:
  application:
    name: payment-orch

camunda:
  client:
    zeebe:
      broker:
        gateway-address: ${ZEEBE_ADDRESS}
        plaintext: true
      defaults:
        worker:
          threads: 3

server:
  port: 8080

logging:
  level:
    com.orchestrpay: DEBUG
    io.camunda.zeebe: WARN